---
- hosts: eip
  gather_facts: yes
  remote_user: ec2-user
  become: yes
  any_errors_fatal: true

  vars:
    - app_root_directory: "/srv/app"

  tasks:
    - name: Ship files to server
      synchronize:
        src: ../../gui/build
        dest: "{{app_root_directory}}/gui"
        rsync_opts:
          - "--exclude=*.map"
        recursive: yes
        delete: yes

    - name: Ensure user has read and write access on all files
      file:
        path: "{{app_root_directory}}"
        owner: ec2-user
        group: ec2-user
        mode: u=rwX,g=rX,o=rX
        recurse: yes
